# 配置项的刷新间隔，以毫秒为单位，如果设置为0，则文件一改动即生效
domain: http://www.lant.ltd
defaultPassword: letgoit
tmc:
  partnerCode: P10000048
  version: 1.0.0
file:
  root: /alidata/own/upload/learn/static/images/
  urlPrefix: http://www.lant.ltd/learn/static/images/
  qrCodePath: /alidata/own/upload/learn/static/images/qrcode/
  qrCodeLogoPath: /alidata/own/upload/learn/static/images/qrcode/logo.jpg